airstats_dbt:
  outputs:
    dev:
      type: snowflake
      account: KWBQOWH-XO35273
      user: DBT_USER
      password: "{{ env_var('DBT_SNOWFLAKE_PASSWORD') }}"
      role: DBT_ROLE
      warehouse: AIRSTATS_DBT_WH
      database: AIRSTATS_DEV
      schema: STAGING
      threads: 4

  target: dev